# Feel free to disable non-critical HA parts during devel by commenting lines out
# Generated in hadk by executing: rpm/dhd/helpers/add_new_device.sh

Description: Pattern with packages for h4113 configurations
Name: jolla-configuration-h4113
Requires:
- pattern:jolla-hw-adaptation-h4113

- patterns-sailfish-applications
- patterns-sailfish-ui
- patterns-sailfish-cellular-apps

- sailfish-content-graphics-z@ICON_RES@

- jolla-settings-networking-multisim

- geoclue-provider-mlsdb
- csd
- jolla-settings-system-flashlight
- mapplauncherd-booster-silica-qt5-media

Summary: Jolla Configuration h4113

